@startuml
class Main{}

class Player{
    - Scanner playerInput;
    - String playerName;
    - ArrayList<String> teamPlayers;

    + String setPlayerName(Scanner input)
}

class Team{
    - String teamName;
    - Scanner teamInput;
    - Scanner writeToFile;
    - Boolean haveLost = false;
    - int gamesWon = 0;
    - int teamID;
    - int teamPoints;
    + int setGamesWon(int won)
    + Boolean setHaveLost(Boolean lost)
    + int setTeamPoints(int teamPoints)
}

class Admin{
    - Scanner writeToFile;
    - Scanner readFromFile;
    - String deadline;
    + String setDeadline()
}

class Date{
    - int day;
    - int month;
    - int year;
    + void setDate(int _day, int _month, int _year)
    + String getDate()
}

class Knockout{
    - ArrayList<Team> teams;
    - Scanner setGameDate;
    - void sortTeams(ArrayList<Team> _teams)
    + void setGameDate(ArrayList<Team> _teams, Scanner input)
    + void printGamePlan(ArrayList<Team> _teams)
}

class Brackets{
    - ArrayList<ArrayList> bracket = new ArrayList<>();
    - ArrayList<Team> teamPlacement = new ArrayList<>()
}

Main <-- Admin
Main <-- Player

Team <-- Player

Admin <-- Knockout
Admin <-- Brackets
Admin <-- Date
Admin <-- Team

Knockout <-- Date
Brackets <-- Date


@enduml